name: Deploy .NET Application to IIS

on:
  push:
    branches:
      - master  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify your .NET version

      - name: Publish .NET Application
        run: dotnet publish -c Release -o ./published

      - name: Copy Files to IIS Server
        run: |
          $session = New-PSSession -ComputerName "20.5.249.244" -Credential (New-Object PSCredential("sahil", (ConvertTo-SecureString "Sahil@1234567" -AsPlainText -Force))) -Port 5985 -Authentication Default
          Copy-Item -Path ./published/* -Destination "C:\inetpub\wwwroot\DefaultWebSite" -Recurse -ToSession $session
          Remove-PSSession -Session $session
        shell: pwsh

      - name: Restart IIS
        run: |
          $session = New-PSSession -ComputerName "20.5.249.244" -Credential (New-Object PSCredential("sahil", (ConvertTo-SecureString "Sahil@1234567" -AsPlainText -Force))) -Port 5985 -Authentication Default
          Invoke-Command -Session $session -ScriptBlock {
            Import-Module WebAdministration
            Restart-WebAppPool -Name "DefaultWebSite"  # Update if your app pool has a different name
          }
          Remove-PSSession -Session $session
        shell: pwsh
