name: Deploy to IIS on Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'  # Replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore BookShoppingCart-Mvc.sln

    - name: Build
      run: dotnet build BookShoppingCart-Mvc.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish BookShoppingCart-Mvc/BookShoppingCart-Mvc.csproj --configuration Release --output ./publish

    - name: Deploy to IIS
      uses: ramyaprathyusha/copy-windows-file@v1.0.0
      with:
        source-dir: ./publish
        destination: '\\YOUR_VM_IP\C$\inetpub\wwwroot\DemoApp'  # Change this to your desired destination
        username: ${{ secrets.IIS_USERNAME }}  # Set this secret in your GitHub repo
        password: ${{ secrets.IIS_PASSWORD }}  # Set this secret in your GitHub repo

    - name: Restart IIS
      run: |
        Invoke-Expression "C:\Windows\System32\iisreset.exe"
      shell: pwsh
