name: Deploy to Azure VM IIS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Adjust according to your application's .NET version

    - name: Restore dependencies
      run: dotnet restore C:\inetpub\wwwroot\MyDemoApp\BookShoppingCart-Mvc

    - name: Build the project
      run: dotnet publish C:\inetpub\wwwroot\MyDemoApp\BookShoppingCart-Mvc -c Release -o ./published

    - name: Copy files to Azure VM
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.IIS_SERVER }}
        username: ${{ secrets.IIS_USERNAME }}
        key: ${{ secrets.IIS_PASSWORD }}
        source: ./published/
        target: 'C:\\inetpub\\wwwroot\\MyDemoApp' # Adjust path if needed

    - name: Run remote command on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IIS_SERVER }}
        username: ${{ secrets.IIS_USERNAME }}
        key: ${{ secrets.IIS_PASSWORD }}
        script: |
          # Restart IIS to apply changes
          iisreset /restart
