name: Deploy to Azure VM IIS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Adjust according to your application's .NET version

    - name: Restore dependencies
      run: dotnet restore BookShoppingCartMvc.sln

    - name: Build the project
      run: dotnet publish BookShoppingCartMvc.sln -c Release -o ./published

    - name: Copy files to Azure VM
      run: |
        $sourcePath = "$(Get-Location)\published\*"
        $destinationPath = "C:\inetpub\wwwroot\MyDemoApp\"
        $session = New-PSSession -HostName "40.82.198.47" -UserName "sahil" -KeyFilePath "$HOME\.ssh\id_rsa" # Ensure this path is correct
        Copy-Item -Path $sourcePath -Destination $destinationPath -ToSession $session

    - name: Restart IIS on Azure VM
      run: |
        $session = New-PSSession -HostName "40.82.198.47" -UserName "sahil" -KeyFilePath "C:\Users\sahil\.ssh\id_rsa" # Ensure this path is correct
        Invoke-Command -Session $session -ScriptBlock { iisreset }
